export const APP_ICONS = {
  brand: 'schedule',
  themeLight: 'light_mode',
  themeDark: 'dark_mode',
  themeSystem: 'desktop_windows',
  navTasks: 'check_circle',
  navTimeEntries: 'schedule',
  navCalendar: 'calendar_month',
  navActivities: 'analytics',
  navSettings: 'settings',
  navAccount: 'account_circle',
  navShowcase: 'palette',
  menuOpen: 'menu',
  menuClose: 'close',
  signOut: 'logout',
  taskFolder: 'folder',
  taskItem: 'task_alt',
  expandMore: 'expand_more',
  expandLess: 'chevron_right',
  add: 'add',
  more: 'more_vert',
  edit: 'edit',
  archive: 'archive',
  unarchive: 'unarchive',
  delete: 'delete',
  empty: 'inbox',
  clear: 'close',
  close: 'close',
  search: 'search',
  chipRemove: 'cancel',
  info: 'info',
  success: 'check_circle',
  warning: 'warning',
  error: 'error',
  time: 'schedule',
  duplicate: 'content_copy',
  block: 'block',
  translate: 'translate',
  openInNew: 'open_in_new',
  favorite: 'favorite',
  viewList: 'view_list',
  viewGrid: 'grid_view',
  viewCard: 'view_module',
} as const;

export type AppIcon = (typeof APP_ICONS)[keyof typeof APP_ICONS];
